# Generated by Django 4.2.2 on 2023-07-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_discountedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('size', models.CharField(max_length=10)),
                ('fabric', models.CharField(max_length=50)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('brand', models.CharField(max_length=50)),
                ('power_rating', models.CharField(max_length=20)),
            ],
            bases=('shop.product',),
        ),
    ]
